apiVersion: apps/v1
kind: Deployment
metadata:
  name: bayesianas
  labels:
    app: bayesianas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bayesianas
  template:
    metadata:
      labels:
        app: bayesianas
    spec:
      containers:
        - name: bayesianas
          image: mauriballes/bayesianas:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
